name: 'Packer validate'
author: 'Dawit Nida <dawit@dawitnida.com>'
description: 'Validate packer template file in a directory'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-circle'
  color: 'blue'